name: Black
on: [pull_request, push]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
        id: black
      - name: If needed, commit black changes to the pull request
        run: echo Output is ${{steps.black}}
#         if: steps.black.
#         uses: peter-evans/create-pull-request@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           title: "Format Python code with psf/black push"
#           commit-message: ":art: Format Python code with psf/black"
#           body: |
#             There appear to be some python formatting errors in ${{ github.sha }}. This pull request
#             uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
#           base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
#           branch: actions/black
    
